### ISSUE TITLE
Suppose the whole cache is loaded for processing, no further data could be added into the cache

### ISSUE THREAD

**Issue by elenaviter** [ImpalaToGo/ImpalaToGo#22]
In case if cache is completely loaded for processing, and new data is requested, new data request is being rejected by cache due the size limit exceeded.
Proposed solution is - given with the defined condition - supply direct handles to remote data if LRU cache rejected new data (bypassing cache).

**Comment by DavidGruzman** [comment]
I suggest that we should track "datasets". This is sets of files related to the same query. In this case we should implement LRU between datasets and MRU inside dataset. 
The reason is that if the same dataset is reused it is likely to be reused in the same order and then LRU is worst possible strategy.
