### ISSUE TITLE
the way we wait for instances is not optimal

### ISSUE THREAD

**Issue by DavidGruzman** [ImpalaToGo/ImpalaToGo#34]
We are doing keyscan. There is suggestion that checking instance status is better.
Indeed i have example when all instances are already available, but out scripts still doing key scan

**Comment by navado** [comment]
You have to do keyscan for multiple reasons:
1. To know when instance is ready for SSH connection (keyscan starts when AWS reports that instance ready)
2. To discover SSH key to be able to connect (otherwise you'll need to type yes or find some other hack barely suitable for automation)

Which problem do you see with keyscan?

**Comment by DavidGruzman** [comment]
My only problem that I have impression, (possible wrong) that there is delay between instance actually available and keyscan succeed. If it is wrong impresison - whole issue should be closed.

**Comment by navado** [comment]
The issue, probably, is in fact that part of instances are ready early when part delayed. We wait for all because in bash it's hard to impossible to make complex event-driven handling.
